<a href="https://colab.research.google.com/github/Wikanda-Hongboonmee/data_viz_2022/blob/main/Project_DataViz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Project กลุ่ม**

* ทำ Dashboard ของ Data Covid (ตั้งแต่วันที่ 12/01/2020 - 18/03/2022) 
* ใช้ข้อมูลภูมิภาค 
* ข้อมูลอื่นที่เลือกเอง

# **รายชื่อสมาชิกในกลุ่ม**
**ชื่อกลุ่ม** : ไข่ดาวเจียว

1.  นางสาวสุภาภรณ์ บุตุธรรม  623020543-8 
2.  นายคำแสน  แก้วพิภพ       623020761-8
3.  นางสาววิกานดา หงษ์บุญมี  623020764-2

***Basic Programming for Data Science and Data Visualization***

In [1]:
import pandas as pd  # pandas เป็น Package ที่ใช้เกี่ยวกับการจัดการข้อมูลที่เป็นตาราง , เรียกใช้โดยการ import แล้วตามด้วยชื่อ Package

In [2]:
from google.colab import drive  # เชื่อมต่อกับ google drive ที่เราเก็บข้อมูลไว้
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os # เป็น package ที่เอาไว้จัดการไฟล์และเอาไว้ดูที่มาของไฟล์หรือ path

In [4]:
path = '/content/drive/My Drive/Project_DataViz2022' #ระบุให้ชี้ไปที่โฟลเดอร์ใน google drive ที่เราเซฟไฟล์ไว้ คือ โฟลเดอร์ Project_DataViz2022

# **ชุดข้อมูลที่ 1**

In [5]:
data_01 = pd.read_csv(os.path.join(path,'confirmed-cases.csv')) # ไฟล์ที่เราต้องการ
data_01 # print data ดูว่ามันหน้าตาเป็นยังไง

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
...,...,...,...,...,...,...,...,...,...,...,...
839766,839767,12/8/2021,11/8/2021,ชาย,52.0,ปี,NaN,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839767,839768,12/8/2021,11/8/2021,ชาย,34.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839768,839769,12/8/2021,11/8/2021,ชาย,31.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839769,839770,12/8/2021,11/8/2021,ชาย,83.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839770,839771,12/8/2021,11/8/2021,ชาย,47.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN

# **ชุดข้อมูลที่ 2**

In [6]:
data_02 = pd.read_csv(os.path.join(path,'confirmed-cases-since-120864.csv')) # ไฟล์ที่เราต้องการ
data_02 # print data ดูว่ามันหน้าตาเป็นยังไง

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,816990,12/8/2021,11/8/2021,ชาย,7.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN
1,816991,12/8/2021,11/8/2021,ชาย,1.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN
2,816992,12/8/2021,11/8/2021,ชาย,35.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN
3,816993,12/8/2021,11/8/2021,หญิง,33.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN
4,816994,12/8/2021,11/8/2021,หญิง,14.0,ปี,Thailand,เชียงราย,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1042163,1859153,25/10/2021,24/10/2021,ชาย,45.0,ปี,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
1042164,1859154,25/10/2021,24/10/2021,ชาย,31.0,ปี,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
1042165,1859155,25/10/2021,24/10/2021,ชาย,31.0,ปี,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
1042166,1859156,25/10/2021,24/10/2021,ชาย,24.0,ปี,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
1042167,1859157,25/10/2021,24/10/2021,ชาย,25.0,ปี,NaN,เชียงใหม่,ทัณฑสถาน/เรือนจำ,NaN,NaN

# **ชุดข้อมูลที่ 3**

In [7]:
data_03 = pd.read_csv(os.path.join(path,'confirmed-cases-since-271064.csv')) # ไฟล์ที่เราต้องการ
data_03 # print data ดูว่ามันหน้าตาเป็นยังไง

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset,Unnamed: 11
0,1859158,26/10/2021,25/10/2021,ชาย,20.0,ปี,Thailand,ลำปาง,อื่นๆ,ลำปาง,เมืองลำปาง,NaN
1,1859159,26/10/2021,25/10/2021,หญิง,42.0,ปี,Thailand,ลำปาง,อื่นๆ,ลำปาง,เมืองลำปาง,NaN
2,1859160,26/10/2021,25/10/2021,หญิง,33.0,ปี,Thailand,ลำปาง,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร,NaN
3,1859161,26/10/2021,25/10/2021,หญิง,52.0,ปี,Thailand,ลำปาง,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร,NaN
4,1859162,26/10/2021,25/10/2021,หญิง,84.0,ปี,Thailand,ลำปาง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ลำปาง,เมืองลำปาง,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1010454,2869612,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN
1010455,2869613,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN
1010456,2869614,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,ปัตตานี,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN
1010457,2869615,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,ปัตตานี,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN
1010458,2869616,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,ปัตตานี,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN

# **ชุดข้อมูลที่ 4**

In [8]:
data_04 = pd.read_csv(os.path.join(path,'confirmed-cases-since-280265.csv')) # ไฟล์ที่เราต้องการ
data_04 # print data ดูว่ามันหน้าตาเป็นยังไง

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,2869617,28/2/2022,27/2/2022,ชาย,41.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
1,2869618,28/2/2022,27/2/2022,หญิง,45.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
2,2869619,28/2/2022,27/2/2022,หญิง,40.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
3,2869620,28/2/2022,27/2/2022,ชาย,44.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
4,2869621,28/2/2022,27/2/2022,ชาย,11.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
...,...,...,...,...,...,...,...,...,...,...,...
433548,3303165,18/3/2022,17/3/2022,หญิง,NaN,NaN,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
433549,3303166,18/3/2022,17/3/2022,หญิง,NaN,NaN,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
433550,3303167,18/3/2022,17/3/2022,หญิง,NaN,NaN,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
433551,3303168,18/3/2022,17/3/2022,หญิง,NaN,NaN,NaN,สงขลา,ทัณฑสถาน/เรือนจำ,NaN,NaN
433552,3303169,18/3/2022,17/3/2022,หญิง,NaN,NaN,NaN,สงขลา,ทัณฑสถาน/เรือนจำ,NaN,NaN

# **รวมตาราง**

In [9]:
data_covid = pd.concat([data_01, data_02, data_03, data_04])
data_covid

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset,Unnamed: 11
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,NaN
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
433548,3303165,18/3/2022,17/3/2022,หญิง,NaN,NaN,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN
433549,3303166,18/3/2022,17/3/2022,หญิง,NaN,NaN,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN
433550,3303167,18/3/2022,17/3/2022,หญิง,NaN,NaN,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN
433551,3303168,18/3/2022,17/3/2022,หญิง,NaN,NaN,NaN,สงขลา,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN
433552,3303169,18/3/2022,17/3/2022,หญิง,NaN,NaN,NaN,สงขลา,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN

## **ตรวจสอบค่า Missing ของตาราง data_covid**

In [10]:
data_covid.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง สรุปคือทุกคอลัมน์ไม่มีค่า  missing

No.                      False
announce_date            False
Notified date             True
sex                       True
age                       True
Unit                      True
nationality               True
province_of_isolation     True
risk                      True
province_of_onset         True
district_of_onset         True
Unnamed: 11               True
dtype: bool

### **แก้ค่า Missing ของคอลัมน์ 'age'**

In [11]:
# แทนค่า Missing ของคอลัมน์ 'age' ด้วยค่า mean ของ 'age'
data_covid[['age']].mean()       
avg_age = data_covid[['age']].mean() 
data_covid[['age']] = data_covid[['age']].fillna(avg_age)   # แทนค่าเฉลี่ยของอายุลงไปในค่าว่าง

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  This is separate from the ipykernel package so we can avoid doing imports until

In [12]:
data_covid.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง จะเห็นว่าคอลัมน์ 'age' เป็น False นั่นคือไม่มีค่า missing

No.                      False
announce_date            False
Notified date             True
sex                       True
age                       True
Unit                      True
nationality               True
province_of_isolation     True
risk                      True
province_of_onset         True
district_of_onset         True
Unnamed: 11               True
dtype: bool

### **แก้ค่า Missing ของคอลัมน์ 'risk'**

In [13]:
set(data_covid['risk'])      # ลองดู set ข้อมูลของคอลัมน์ 'risk'

{' Samui plus',
 '10.อื่นๆ',
 '2.สัมผัสผู้ติดเชื้อ',
 '8.สำรวจกลุ่มเสี่ยง (survey)',
 '9.ขอตรวจหาเชื้อเอง',
 'ACF รองเมือง',
 'ACF สนามกีฬาธูปะเตมีย์',
 'ACF สนามกีฬาไทย-ญี่ปุ่น',
 'ACF สีลม',
 'ACF เคหะหลักสี่',
 'BKK Sandbox',
 'Chonburi Sandbox',
 'Cluster Icon siam',
 "Cluster Memory 90's กรุงเทพมหานคร",
 'Cluster New Jazz กรุงเทพมหานคร',
 'Cluster The Lounge Salaya',
 'Cluster คลองเตย',
 'Cluster งานมอเตอร์ โชว์',
 'Cluster จนท. สนามบินสุวรรณภูมิ',
 'Cluster จันทบุรี',
 'Cluster จันทบุรี (ชาวกินี )',
 'Cluster จันทบุรี (ชาวกินี)',
 'Cluster ชลบุรี',
 'Cluster ชลบุรี บริษัทไดกิ้น',
 'Cluster ชลบุรี โรงเบียร์ 90',
 'Cluster ตราด',
 'Cluster ตราด ',
 'Cluster ตลาดนนทบุรี',
 'Cluster ตลาดบางพลี',
 'Cluster ตลาดบางแค',
 'Cluster ตลาดพรพัฒน์',
 'Cluster ตลาดสี่มุมเมือง',
 'Cluster บริษัทศรีสวัสดิ์',
 'Cluster บางแค',
 'Cluster บ่อนพัทยา/ชลบุรี',
 'Cluster บ่อนเทพารักษ์',
 'Cluster บ่อนไก่อ่างทอง',
 'Cluster ปากช่อง',
 'Cluster ผับ Thonglor',
 'Cluster มหาสารคาม',
 'Cluster ระยอง',
 'Cluster สถานบันเทิงย่านทองหล่อ',
 'Cluster สมุทรปราการ (โรงงาน บริษัทเมทัล โปรดักส์)',
 'Cluster สมุทรปราการ GRP Hightech',
 'Cluster สมุทรปราการ ตลาดเคหะบางพลี',
 'Cluster สมุทรสาคร',
 'Cluster ห้างแสงทอง (สายล่าง)',
 'Cluster เครือคัสเซ่อร์พีคโฮลดิ้ง (CPG,CPH)',
 'Cluster โรงงาน Big Star',
 'Cluster โรงงาน QPP ประจวบฯ',
 'Cluster โรงงาน standard can',
 'Cluster โรงงานทำขนม บางขุนเทียน',
 'Karbi Sandbox',
 'Krabi Sandbox',
 'Krabi Sandbox ',
 'Krabi sandbox ',
 'Narathiwat Sandbox',
 'Phang Nga Sandbox',
 'Phang nga Sandbox',
 'Phangnga Sandbox',
 'Phare Sandbox',
 'Phrae Sandbox',
 'Phuket Sandbox',
 'Phunga Sandbox',
 'Prachuap Sandbox',
 'Rayong Sandbox',
 'SHUI',
 'Samui Plus',
 'Samui plus',
 'Samut Prakan Sandbox',
 'Sandbox',
 'Songkhla Sandbok',
 'State Quarantine',
 'Surin Sandbox',
 'Test and Go',
 'Trat Sandbox',
 'Trat sandbox',
 'Udon Sandbox',
 'cluster ชลบุรี\n(อยู่ระหว่างการสอบสวน)',
 nan,
 'prachuap Sandbox',
 'กลับมาจาก จ.กรุงเทพมหานคร.',
 'การค้นหาผู้ป่วยเชิงรุกและค้นหาผู้ติดเชื้อในชุมชน',
 'คนต่างชาติเดินทางมาจากต่างประเทศ',
 'คนไทยมาจากพื้นที่เสี่ยง',
 'คนไทยเดินทางกลับจากต่างประเทศ',
 'คนไทยเดินทางมาจากต่างประเทศ',
 'ค้นหาเชิงรุก',
 'ตรวจก่อนทำหัตถการ',
 'ตรวจก่อนทำหัถตการ',
 'ตรวจสุขภาพแรงงานต่างด้าว',
 'ตลาด',
 'ติดเชื้อในพื้นที่ (สัมผัส ผป.ยืนยัน)',
 'ทัณฑสถาน/เรือนจำ',
 'นักกีฬา',
 'บุคลากรด้านการแพทย์และสาธารณสุข',
 'บุคลากรทางการเเพทย์',
 'ปอดอักเสบ (Pneumonia)',
 'ปอดอักเสบ Pneumonia',
 'ปอดอักเสบ(Pneumonia)',
 'ผับหัวหิน',
 'ผู้ติดเชื้อในประเทศ',
 'ผู้ที่เดินทางมาจากต่างประเทศ และเข้า AOQ',
 'ผู้ที่เดินทางมาจากต่างประเทศ และเข้า AQ',
 'ผู้ที่เดินทางมาจากต่างประเทศ และเข้า ASQ/ALQ',
 'ผู้ที่เดินทางมาจากต่างประเทศ และเข้า HQ/AHQ',
 'ผู้ที่เดินทางมาจากต่างประเทศ และเข้า OQ',
 'ผู้ป่วย PUI',
 'ผู้ป่วย กรุงเทพมหานคร',
 'ผู้เดินทางมาจากพื้นที่เสี่ยง กรุงเทพมหานคร',
 'พิธีกรรมทางศาสนา',
 'พื้นที่เสียง',
 'มาจากพื้นที่เสียง จ.ปทุมธานี',
 'มาจากพื้นที่เสี่ยง',
 'มาจากพื้นที่เสี่ยง จ.ปทุมธานี',
 'มีอาการ มาจาก กรุงเทพมหานคร. พนักงานร้านอาหาร',
 'รอประสาน',
 'ระบุไม่ได้',
 'ระหว่างการสอบสวนโรค',
 'ระหว่างสอบสวน',
 'รับจ้างขนของที่ตลาดท่ายาง',
 'ร่วมงานศพในหมู่บ้านทุกวัน',
 'ร้านอาหาร',
 'ศูนย์กักกัน ผู้ต้องกัก',
 'สถานที่ทำงาน',
 'สถานบันเทิง',
 'สถานประกอบการ',
 'สถานศึกษา',
 'สน.วัดพระยาไกร',
 'สนามมวย',
 'สัมผัสผู้ติดเชื้อยืนยัน\n  อยู่ระหว่างสอบสวน',
 'สัมผัสผู้ติดเชื้อยืนยัน\nอยู่ระหว่างสอบสวน',
 'สัมผัสผู้ป่วยที่ติดโควิด',
 'สัมผัสผู้ป่วยยืนยัน',
 'สัมผัสผู้ป่วยยืนยัน \n  อยู่ระหว่างสอบสวน',
 'สัมผัสผู้ป่วยยืนยัน (ยังไม่สามารถระบุได้)',
 'สัมผัสผู้ป่วยยืนยัน ภายในครอบครัว/ชุมชน/เพื่อน',
 'สัมผัสผู้ป่วยยืนยัน อยู่ระหว่างสอบสวน',
 'สัมผัสผู้ป่วยยืนยันภายในชุมชน',
 'สัมผัสผู้ป่วยยืนยันเพื่อนร่วมงาน',
 'สัมผัสผู้เดินทางจากต่างประเทศ',
 'สัมผัสสามีสะอาด เขตบ้าน (รพ.มหาชัย 2)',
 'สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้',
 'สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้ใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้',
 'สัมผัสใกล้ชิดผู้ป่วยยันยันก่อนหน้า',
 'สัมผัสใกล้ชิดผู้ป่วยยืนยันก่อนหน้า',
 'สัมผัสในสถานพยาบาล',
 'อยู่ระหว่างการสอบสวน',
 'อยู่ระหว่างการสอบสวน\n',
 'อยู่ระหว่างสอบสวน',
 'อยู่ระหว่างสอบสวนโรค',
 'อาชีพเสี่ยง',
 'อาชีพเสี่ยง เช่น ทำงานในสถานที่แออัด หรือทำงานใกล้ชิดสัมผัสชาวต่างชาติ เป็นต้น',
 'อิ่นๆ',
 'อื่น',
 'อื่น ๆ',
 'อื่นๆ',
 'เดินทางจากพื้นที่เสี่ยง',
 'เดินทางมาจากพื้นที่จังหวัดเสี่ยง',
 'เดินทางมาจากพื้นที่มีการระบาดของโรค',
 'เดินทางมาจากพื้นที่ระบาด',
 'เดินทางมาจากพื้นที่เสี่ยง จ.กรุงเทพฯ จอมทอง',
 'เดินทางมาจากพื้นที่เสี่ยงที่มีการระบาดของโรค',
 'เพื่อเฝ้าระวังเชื้อกลายพันธุ์',
 'แรงงานต่างด้าวตรวจก่อนขึ้นทะเบียน',
 'ในพื้นที่',
 'ไปยัง/มาจาก พื้นที่ระบาดกรุงเทพมหานคร',
 'ไปยังพื้นที่ที่มีการระบาด',
 'ไปสถานที่ชุมชน',
 'ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว',
 'ไปสถานที่เสี่ยง เช่น ตลาด สถานที่ชุมชน',
 'ไปสถานที่แออัด เช่น งานแฟร์ คอนเสิร์ต',
 'ไปเที่ยวสถานบันเทิงในอุบลที่พบการระบาดของโรค Ubar',
 'ไปแหล่งชุมชน/สถานที่คนหนาแน่น',
 'ไม่ระบุ'}

In [14]:
data_covid[['risk']] = data_covid[['risk']].fillna('ไม่มีข้อมูล')  # แทนค่า Missing ของคอลัมน์ 'risk' ด้วย 'ไม่มีข้อมูล'

In [15]:
data_covid.isnull().any()       # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง จะเห็นว่าคอลัมน์ 'risk' เป็น False นั่นคือไม่มีค่า missing

No.                      False
announce_date            False
Notified date             True
sex                       True
age                       True
Unit                      True
nationality               True
province_of_isolation     True
risk                     False
province_of_onset         True
district_of_onset         True
Unnamed: 11               True
dtype: bool

### **แก้ค่า Missing ของคอลัมน์ 'province_of_isolation'**

In [16]:
# ลองดู set ข้อมูลของคอลัมน์ 'province_of_isolation'
set(data_covid['province_of_isolation'])

{nan,
 'กทม',
 'กระบี่',
 'กรุงเทพมหานคร',
 'กาญจนบุรี',
 'กาฬสินธุ์',
 'กำแพงเพชร',
 'ขอนแก่น',
 'ขอนแก่น\xa0',
 'จันทบุรี',
 'ฉะเชิงเทรา',
 'ชลบุรี',
 'ชัยนาท',
 'ชัยภูมิ',
 'ชุมพร',
 'ตรัง',
 'ตราด',
 'ตาก',
 'นครนายก',
 'นครปฐม',
 'นครพนม',
 'นครราชสีมา',
 'นครศรีธรรมราช',
 'นครสวรรค์',
 'นนทบุรี',
 'นราธิวาส',
 'น่าน',
 'บึงกาฬ',
 'บุรีรัมย์',
 'ปทุมธานี',
 'ประจวบคีรีขันธ์',
 'ปราจีนบุรี',
 'ปัตตานี',
 'พระนครศรีอยุธยา',
 'พะเยา',
 'พังงา',
 'พัทลุง',
 'พิจิตร',
 'พิษณุโลก',
 'ภููเก็ต',
 'ภูเก็ต',
 'มหาสารคาม',
 'มุกดาหาร',
 'ยะลา',
 'ยโสธร',
 'ระนอง',
 'ระยอง',
 'ราชบุรี',
 'ร้อยเอ็ด',
 'ลพบุรี',
 'ลำปาง',
 'ลำพูน',
 'ศรีสะเกษ',
 'สกลนคร',
 'สงขลา',
 'สตูล',
 'สมุทรปราการ',
 'สมุทรสงคราม',
 'สมุทรสาคร',
 'สระบุรี',
 'สระแก้ว',
 'สิงห์บุรี',
 'สุพรรณบุรี',
 'สุราษฎร์ธานี',
 'สุรินทร์',
 'สุโขทัย',
 'หนองคาย',
 'หนองบัวลำภู',
 'อำนาจเจริญ',
 'อุดรธานี',
 'อุตรดิตถ์',
 'อุทัยธานี',
 'อุบลราชธานี',
 'อ่างทอง',
 'เชียงราย',
 'เชียงใหม่',
 'เพชรบุรี',
 'เพชรบูรณ์',
 'เลย',
 'แพร่',
 'แม่ฮ่องสอน'}

In [17]:
# แทนค่า Missing ของคอลัมน์ 'province_of_isolation' ด้วย 'ไม่มีข้อมูล'
data_covid[['province_of_isolation']] = data_covid[['province_of_isolation']].fillna('ไม่มีข้อมูล')

In [18]:
data_01.isnull().any()  # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง จะเห็นว่าคอลัมน์ 'province_of_isolation' เป็น False นั่นคือไม่มีค่า missing

No.                      False
announce_date            False
Notified date             True
sex                       True
age                       True
Unit                      True
nationality               True
province_of_isolation     True
risk                      True
province_of_onset         True
district_of_onset         True
dtype: bool

### **แก้ค่า Missing ของคอลัมน์ 'province_of_onset'**

In [19]:
set(data_covid['province_of_onset'])     # ลองดู set ข้อมูลของคอลัมน์ 'province_of_onset'

{'\tประจวบคีรีขันธ์',
 'USA',
 nan,
 '\xa0กาญจนบุรี',
 '\xa0ชลบุรี',
 '\xa0ตราด',
 '\xa0นครปฐม',
 '\xa0สมุทรสงคราม',
 '\xa0สมุทรสาคร',
 '\xa0อุทัยธานี',
 'กทม',
 'กทม.',
 'กบินทร์บุรี',
 'กระบี่',
 'กระบี่ี่',
 'กรุงเทพ',
 'กรุงเทพมหานคร',
 'กรุงเทพมหานคร.',
 'กรุงเทพมหานคร. / พระนครศรีอยุธยา',
 'กรุงเทพมหานคร. / ศรีสะเกษ',
 'กรุงเทพฯ',
 'กะทู้',
 'กัมพูชา',
 'กาญจนบุรี',
 'กาญจบุรี',
 'กาญนบุรี',
 'กาฬสิน',
 'กาฬสินธิ์',
 'กาฬสินธุ์',
 'กาฬสินธุ์\xa0',
 'กาฬสินธ์',
 'กำเพงเพชร',
 'กำแพง',
 'กำแพงเพชร',
 'กำแพงเพชร\xa0',
 'กําแพงเพชร',
 'ขอนแก่น',
 'ขอนแก่น\xa0',
 'ขอนแก่่น',
 'ขัยนาท',
 'ขัยภูมิ',
 'ขานุวรลักษณ์บุรี',
 'คนไทยเดินทางกลับจากต่างประเทศ',
 'คลองเตย',
 'จ.กรุงเทพมหานคร',
 'จ.ภูเก็ต',
 'จ.ราชบุรี',
 'จ.สุราษฎร์ธานี',
 'จังหวัดสมุทรสาคร',
 'จันทบุรี',
 'ฉะเชองเทราร',
 'ฉะเชิงเทรา',
 'ชมพร',
 'ชลบุรี',
 'ชลบุรี\t',
 'ชลบุรี\xa0',
 'ชลบุุรี',
 'ชอนแก่น',
 'ชัยนาถ',
 'ชัยนาท',
 'ชัยบาดาล',
 'ชัยภูมิ',
 'ชัยภูมิ\xa0',
 'ชุมพร',
 'ชุุมพร',
 'ชุุุมพร',
 'ดอนมดแดง',
 'ดินแดง',
 'ตรัง',
 'ตรััง',
 'ตราด',
 'ตราด\xa0',
 'ตาก',
 'ตากใบ',
 'ต่างจังหวัด',
 'ทุ่งเสลี่ยม',
 'ท้ายบ้าน',
 'ธารโต',
 'นคนปฐม',
 'นคปฐม',
 'นครนปฐม',
 'นครนาชสีมา',
 'นครนายก',
 'นครปฐม',
 'นครปฐม\xa0',
 'นครปบม',
 'นครพนม',
 'นครพนม\xa0',
 'นครยายก',
 'นครราขสีมา',
 'นครราชธานี',
 'นครราชศรีมา',
 'นครราชสสีมา',
 'นครราชสีมา',
 'นครราชสีมา ลพบุรี',
 'นครราชสีมา\xa0',
 'นครศรธรรมราช',
 'นครศรี',
 'นครศรีธรมมราช',
 'นครศรีธรมราช',
 'นครศรีธรรมราข',
 'นครศรีธรรมราช',
 'นครศรีฯ',
 'นครศรีีธรรมราช',
 'นครศร๊ธรรมราช',
 'นครศร๊ะรรมราช',
 'นครสรรค์',
 'นครสรีธรรมราช',
 'นครสวรรค',
 'นครสวรรค์',
 'นครสวรรค์\xa0',
 'นครสีธรรมราช',
 'นครฯ',
 'นคราชสีมา',
 'นครีศรีธรรมราช',
 'นตรนายก',
 'นตรปฐม',
 'นนทบุรี',
 'นนทบุรี\xa0',
 'นนทบุุรี',
 'นนทุบรี',
 'นนทุรี',
 'นนมบุรี',
 'นรศรีธรรมราช',
 'นราธิวาส',
 'นราธิวาส\u200b',
 'นราธฺวาส',
 'นอกเขต',
 'นาราธิวาส',
 'นาวัง',
 'น่าน',
 'น่าน/ฉะเชิงเทรา',
 'บางกรวย',
 'บางกะปิ',
 'บางนา',
 'บางปะอิน',
 'บางละมุง',
 'บางศรีเมือง',
 'บางเพียง',
 'บึงกาฬ',
 'บึงโขงหลง',
 'บุรีรัมภ์',
 'บุรีรัมย์',
 'บุรีรัมย์\xa0',
 'บุรีรัยม์',
 'บุรีรีมย์',
 'บ้านหลวง',
 'ปจ',
 'ปทึมธานี',
 'ปทุทธานี',
 'ปทุมฑานี',
 'ปทุมทานี',
 'ปทุมธาน',
 'ปทุมธานี',
 'ปทุมธานี.',
 'ปทุมธานี\xa0',
 'ปทุมธานีี',
 'ปทุมาธานี',
 'ปทุุมธานี',
 'ปธุมธานี',
 'ปมุมธานี',
 'ประจวนคีรีขันธ็',
 'ประจวบ',
 'ประจวบคิรีขันธ์',
 'ประจวบคีรขันธ์',
 'ประจวบคีรขัันธ์',
 'ประจวบคีรีขัน',
 'ประจวบคีรีขันธื',
 'ประจวบคีรีขันธฺ',
 'ประจวบคีรีขันธ์',
 'ประจวบคีรีขันธ์\xa0',
 'ประจวบคีรีขันธ์์',
 'ประจวบคีรีขัันธ์',
 'ประจวบคีีรีขันธ์',
 'ประจวบฯ',
 'ประทุมธานี',
 'ประเทศกัมพูชา',
 'ปราจีนบุรี',
 'ปราจีบุรี',
 'ปลวกแดง',
 'ปลายพระยา',
 'ปอยเปต',
 'ปัตตนรี',
 'ปัตตานนี',
 'ปัตตานี',
 'ปัตตานีี',
 'ปัตาตานี',
 'ปัว',
 'ปััตตานี',
 'ปุทมธานี',
 'ป่าโมก',
 'พม่า',
 'พรหมพิราม',
 'พระนครศรียุธยา',
 'พระนครศรีอยุทธยา',
 'พระนครศรีอยุทยา',
 'พระนครศรีอยุธยา',
 'พระนครศรีอยุธยา\xa0',
 'พะเยา',
 'พังงา',
 'พัทยา',
 'พัทลุง',
 'พัทลุุง',
 'พัังงา',
 'พิจิตร',
 'พิษณุโลก',
 'พิษณุโลก\xa0',
 'พิษณูโลก',
 'ฟินแลนด์',
 'ภาษีเจริญ',
 'ภุเก็ต',
 'ภูุเก็ต',
 'ภููเก็ต',
 'ภูเก็ต',
 'ภูเก็็ต',
 'ภูเพียง',
 'มหาสาคาม',
 'มหาสารคาม',
 'มาเลเซีย',
 'มุกดาหาร',
 'มุกาดหาร',
 'ยะลา',
 'ยานนาวา',
 'ยโสธร',
 'ร.จ.จ.นราธิวาส',
 'รอ',
 'ระนอง',
 'ระบุ',
 'ระยอง',
 'ระยอง\xa0',
 'ระอยง',
 'ราชบบุรี',
 'ราชบุรี',
 'ราชบุรีี',
 'ราชบุรี\u200b',
 'ราชุรี',
 'ราชเทวี',
 'ร้องกวาง',
 'ร้อยเอ็ด',
 'ลบุรี',
 'ลพบุรี',
 'ลพบุรี.',
 'ลพบุรี\xa0',
 'ลอง',
 'ลาดกระบัง',
 'ลาดพร้าว',
 'ลาว',
 'ลำปาง',
 'ลำพูน',
 'ลำพูน\u200b',
 'ลำพููน',
 'ลำลูกกา',
 'วังชิ้น',
 'วังทอง',
 'วิเศษชัยชาญ',
 'ศรีษะสะเกษ',
 'ศรีษะเกษ',
 'ศรีสระเกษ',
 'ศรีสะเกษ',
 'ศีรสะเกษ',
 'สกลนคร',
 'สครสวรรค์',
 'สงขลา',
 'สงขลา\u200b',
 'สตูล',
 'สถานที่ทำงาน',
 'สพรรณบุรี',
 'สมถทรปราการ',
 'สมทรสงคราม',
 'สมทรสาคร',
 'สมุครปราการ',
 'สมุครสาคร',
 'สมุท',
 'สมุทปราการ',
 'สมุทรปรากร',
 'สมุทรปรากรร',
 'สมุทรปรากา',
 'สมุทรปราการ',
 'สมุทรปราการ\xa0',
 'สมุทรศาคร',
 'สมุทรสงคราม',
 'สมุทรสาคร',
 'สมุทรสาคร\xa0',
 'สมุทรสาคา',
 'สมุทรสาคาร',
 'สมุทรสาทร',
 'สมุทรสารคร',
 'สมุทราปราการ',
 'สมุทราสาคร',
 'สมุทสงคราม',
 'สมุทสาคร',
 'สมุย',
 'สมุุทรปราการ',
 'สมุุทรสงคราม',
 'สมุุทรสาคร',
 'สระก้ว',
 'สระบุรี',
 'สระบุรี\xa0',
 'สระแก้ว',
 'สรินทร์',
 'สวิสเซอร์แลนด์',
 'สอง',
 'สองแคว',
 'สะพานสูง',
 'สะแก้ว',
 'สัตหีบ',
 'สัมผัสผู้ป่วยยืนยัน COVID20',
 'สามุทรสาคร',
 'สารคาม',
 'สารภี',
 'สิงห์บุรี',
 'สิงห์บุรี\xa0',
 'สุทรปราการ',
 'สุพรรญบุรี',
 'สุพรรณบุรั',
 'สุพรรณบุรี',
 'สุพรรณบุรี\xa0',
 'สุมทรปราการ',
 'สุมทรสาคร',
 'สุมุทรปราการ',
 'สุมุทรสาคร',
 'สุระบุรี',
 'สุราษ',
 'สุราษฎณ์ธานี',
 'สุราษฎธานี',
 'สุราษฎร์',
 'สุราษฎร์ธานี',
 'สุราษฎร์ฯ',
 'สุราษฎร์์ธานี',
 'สุราษฎ์ธานี',
 'สุราษฏร์ธานี',
 'สุราษธานี',
 'สุราษร์ฎธานี',
 'สุราษร์ธานี',
 'สุราษฯ',
 'สุรินทรื',
 'สุรินทร์',
 'สุรินทร์ 32150',
 'สุรินทร์,รีสะเกษ',
 'สุรินทร์\xa0',
 'สุริมทร์',
 'สุริะแก้ว',
 'สุวรรณภูมิ',
 'สุุพรรณบุรี',
 'สุุราษฎร์ธานี',
 'สุุราษฏร์ธานี',
 'สุุราษฯ',
 'สุุรินทร์',
 'สุุุโขทัย',
 'สุโขทับ',
 'สุโขทัย',
 'สุโขทัย\xa0',
 'สูงเม่น',
 'หนวงบัวลำภู',
 'หนองคาย',
 'หนองงคาย',
 'หนองบัวภู',
 'หนองบัวลำพูน',
 'หนองบัวลำภู',
 'หนองบัวลําภู',
 'หนองบััวลำภู',
 'หนองม่วงไข่',
 'หนอบัวลำภู',
 'หลายจังหวัด',
 'หัวหิน',
 'ห้วยขวาง',
 'อยุทธยา',
 'อยุธยา',
 'อยุุธยา',
 'อำนาจเจริญ',
 'อำนาจเจิญ',
 'อำนาญเจริญ',
 'อำนาเจริญ',
 'อิสราเอล',
 'อุดธานี',
 'อุดร',
 'อุดรธาณี',
 'อุดรธานี',
 'อุดรธานี\xa0',
 'อุดรธานีี',
 'อุดรราชธานี',
 'อุตรดิตถ์',
 'อุตรดิตถ์\xa0',
 'อุตรดิตถ์์',
 'อุตรดิษถ์',
 'อุตรดิิตถ์',
 'อุตรติดถ์',
 'อุทัยธานี',
 'อุทัยานี',
 'อุบลราขธานี',
 'อุบลราชธานี',
 'อุบลราชธานี\xa0',
 'อุุครดิตถ์',
 'อุุดรธาน',
 'อุุดรธานี',
 'อุุตรดิตถ์',
 'อุุทัยธานี',
 'อุุบลราชธานี',
 'อ่งทอง',
 'อ่างทอง',
 'อ่างทอง\xa0',
 'อํานาจเจริญ',
 'เชิงเทรา',
 'เชียงราย',
 'เชียงใหม่',
 'เชียรใหญ่',
 'เชีียงราย',
 'เชีียงใหม่',
 'เด่นชัย',
 'เพขรบุรี',
 'เพขรบูรณื',
 'เพขรบูรณ์',
 'เพชรบุรณ์',
 'เพชรบุรี',
 'เพชรบุรึ',
 'เพชรบุุรี',
 'เพชรบุูรณ์',
 'เพชรบูรณ์',
 'เพชรบูรณ์\xa0',
 'เพชรบูร์',
 'เพชรบููรณ์',
 'เมือง',
 'เมืองตาก',
 'เมืองน่าน',
 'เมืองปัตตานี',
 'เรือ',
 'เลย',
 'เลย\xa0',
 'เวียงจันทร์',
 'เวียงสา',
 'แพร่',
 'แม่ทะ',
 'แม่ฮ่องสอน',
 'แล้วป่วย',
 'โพธิ์ทอง',
 'ไชโย',
 'ไม่มีชื่อหอพัก',
 'ไม่ระบุ'}

In [20]:
# แทนค่า Missing ของคอลัมน์ 'province_of_onset' ด้วย 'ไม่ระบุ'
data_covid[['province_of_onset']] = data_covid[['province_of_onset']].fillna('ไม่ระบุ')

In [21]:
data_covid.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง จะเห็นว่าคอลัมน์ 'province_of_onset' เป็น False นั่นคือไม่มีค่า missing

No.                      False
announce_date            False
Notified date             True
sex                       True
age                       True
Unit                      True
nationality               True
province_of_isolation    False
risk                     False
province_of_onset        False
district_of_onset         True
Unnamed: 11               True
dtype: bool